### ISSUE TITLE
order of `visual(Contour) * SplitApplyPlot.density()` matters

### ISSUE THREAD

**Issue by jkrumbiegel** [piever/SplitApplyPlot.jl#53]
I noticed that `visual(Contour) * SplitApplyPlot.density()` draws contour lines, but `SplitApplyPlot.density() * visual(Contour)` draws a 2D heatmap. I assume the heatmap is somehow set as the default geom for `density` and is overridden in one case but not the other.

```
data(penguins) *
    mapping(
        :bill_length_mm => (x -> x / 10) => "bill length (cm)",
        :bill_depth_mm => (x -> x / 10) => "bill depth (cm)",
        color = :species) *
    (visual(Scatter) * visual(strokecolor = :black, alpha = 0.7) +
    SplitApplyPlot.density() * visual(Contour)) |> draw
```

<img width="642" alt="grafik" src="https://user-images.githubusercontent.com/22495855/116781711-0703e480-aa85-11eb-8ccb-5839ebdbf6d9.png">

**Comment by piever** [comment]
What happens is the following:
- `visual(Contour)` only sets to `Contour` the plottype of `Entry`s that do not have a plottype (ie, that are of plottype `Any`)
- `density` sets the plottype to `Heatmap` only if it encounters `Any`

So doing `visual(Contour)` first is the way to prevent `density` from setting `Heatmap`.

Possible fixes:
1. `visual(Contour)` would set the plottype to `Contour` regardless of what it finds
2. add a specialized `Suggested(Heatmap)` plottype, to indicated that it recommends `Heatmap`, but can be overridden by `visual(Contour)`
3. leave as is and document the behavior

Given that `*` is not commutative here, option 3 is less outlandish than it sounds, but I see how it can trip people up. Options 2 seems a bit overcomplicated, maybe just going with 1 is best?

**Comment by jkrumbiegel** [comment]
I see, makes sense. I kind of like option 2, but I know almost nothing about the internals to judge if that makes sense in the grand scheme of things.

But I remember now my previous issue from AlgebraOfGraphics, how one can set geoms for analyses that might even have more than one layered geom. So this issue seems related right? https://github.com/JuliaPlots/AlgebraOfGraphics.jl/issues/87

**Comment by piever** [comment]
At the moment I stopped returning multiple entries but have a unique `LinesFill` recipe for the shaded areas, but I guess this doesn't really scale. For example, I imagine some analyses will return barplots with error bars, so we should tackle that anyway. I'm starting to see that the two issues (default plottype and separate customization) are related and I think there is a common solution.

The key idea is that now there is no distinction between geometry and statistics, there are only transformations that take an `Entry` and return one or more entries. The `density` transformation for example takes an entry, changes the data and, if no plottype is present, adds `Heatmap`. The `visual` transformation adds the plottype if no plottype is present. 

A general solution seems to be:
- make `visual` by default always change the plottype
- also support `visual(plottype1 => plottype2; attributes...)`, which is the identity, unless it encounters `plottype1`, in which case it acts as `visual(plottype2; attributes...)`.

This way the current behavior is achieved with `visual(Any => plottype2; attributes...)`, just `visual(Contour)` would always work to update the plot chosen by `density`, and in more complex cases things should always be possible. For example, if your analyses returns barplot + errorbars and you want to switch to scatter + errorbars and have the errorbars thicker, you'd do:

```julia
analysis * visual(BarPlot => Scatter) * visual(ErrorBar => ErrorBar; linewidth = 3)
# here also `visual(ErrorBar => Any)` would also work, because I think the new plot should be determined
# by calling `plottype` on the result, as in `newplottype = plottype(plottype2, plottype1)`
```

Then in the future we can make this richer by supporting things like `visual(ErrorBar => nothing)` to not show error bars or things like that.

There are mild subtleties to figure out, for example, does it make more sense that `visual(Contour)` changes all and `visual(Any => Contour)` only changes the ones with plottype `Any`, or is the other way around more intuitive? Maybe the first argument of the pair could be a predicate rather than a plottype.

(Sorry about the unstructured reply, but this is still a bit fuzzy in my mind.)

**Comment by piever** [comment]
For now I'm going with the simple solution of always updating plot type when the user passes eg `visual(Scatter)`. Changing plot type selectively (only on some plots) will be handled with the same technique used to change attributes selectively (to be decided, probably the pair syntax).

I'm also changing the order (eg `analysis * visual` rather than viceversa) in the tutorial, so that it can be made to work in the future when one need to decide what to do according to what is returned by `analysis`.

**Comment by jkrumbiegel** [comment]
Is it likely that there would be an analysis with multiple geoms that are the same by default, but of which you'd only want to change one? In this case just doing `Scatter => Lines` would not work right. What about the ability to name the components of an analysis, then one could do `:errorbars => Scatter` even though this example is nonsensical ;)

**Comment by piever** [comment]
I like the idea of naming them! Especially because it allows to use the type (symbol versus `PlotFunc`) to figure out whether it is a selection (symbol), or the new plottype. That way, `visual(:error, linewidth = 10)` is much nicer than `visual(ErrorBars => Errorbars, linewidth = 10)`.

Analyses that return multiple geoms of the same type by default are probably not incredibly common, but I think meaningful names are much better, especially because they will mostly be consistent across analyses. I think `estimate` (or `trend`) and `error` covers most cases (both lines and shades or bars and errorbars), or `lower`, `diagonal`, and `upper` for a `corrplot`. (Getting a nice, configurable `corrplot` is probably a good test that the new system is working.)

**Comment by jkrumbiegel** [comment]
Cool, I agree that `visual(:error, linewidth = 10)` is nicer than `visual(ErrorBars => Errorbars, linewidth = 10)`.

I have actually not seen anything like a corrplot yet from AoG, is there an example somewhere of something with an unusual layout? Or maybe a marginal histogram?

**Comment by piever** [comment]
` supposed to be supported` is the right way to put it :)

It's not available yet, but given that there are column selection, grouping and layout already in AoG, a `corrplot` naturally belongs there, IMO, should be reasonably easy to add.

Mildly off-topic: do you have marginal histogram recipes lying around somewhere (mostly curious what is the best way to add the marginal plots, layout-wise)? I think they can also be added here, it is another good use case of being able to change the marginal plot type (line vs bar, but also kde vs histogram, if that turns out to be possible).

**Comment by jkrumbiegel** [comment]
this is ten months old https://gist.github.com/jkrumbiegel/e721eec3ebfdeb32ad4bc8d2d2ec8efb

I just thought that AoG was kind of "symmetric" for lack of a better word, so I didn't think much about using it for more than single or facet plots. On what level would a margin histogram be set up? `layout`, `col` and `row` keywords wouldn't really work anymore then? Or would they work and just do multiple of those larger plots? That could actually be kind of cool

**Comment by piever** [comment]
I think it's a matter of supporting plots that are plotted into a subfigure, rather then on an axis. Then, yes, `corrplot(somecols, col = somevar)` would make as many corrplots as unique values of `somevar`, concatenated horizontally. Things like `corrplot(somecols, color = somevar)` also look like they might be useful, where within each subplot of the `corrplot` styling happens by color.
